<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('kelas', function (Blueprint $table) {
            // Drop existing foreign key if exists
            // Since we don't know the exact name auto-generated by Laravel in previous migration, 
            // we try standard naming. If it was created as constraint, we need to drop it.
            // Based on error: CONSTRAINT `kelas_dosen_id_foreign`
            $table->dropForeign('kelas_dosen_id_foreign');
            
            // Add new foreign key referencing dosens table
            $table->foreign('dosen_id')
                  ->references('id')
                  ->on('dosens')
                  ->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('kelas', function (Blueprint $table) {
            $table->dropForeign(['dosen_id']);
            
            $table->foreign('dosen_id')
                  ->references('id')
                  ->on('users')
                  ->onDelete('cascade');
        });
    }
};
