<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use App\Traits\Auditable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, Auditable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function admin(): HasOne
    {
        return $this->hasOne(Admin::class);
    }

    public function dosen(): HasOne
    {
        return $this->hasOne(Dosen::class);
    }

    public function mahasiswa(): HasOne
    {
        return $this->hasOne(Mahasiswa::class);
    }

    // Alias for backward compatibility (student = mahasiswa)
    public function student(): HasOne
    {
        return $this->mahasiswa();
    }

    public function parent(): HasOne
    {
        return $this->hasOne(ParentModel::class);
    }

    public function isSuperAdmin(): bool
    {
        return $this->hasRole('super_admin') || $this->role === 'super_admin';
    }

    public function isAdmin(): bool
    {
        return $this->hasRole('akademik') || $this->hasRole('super_admin') || in_array($this->role, ['admin', 'akademik', 'super_admin']);
    }

    public function isDosen(): bool
    {
        return $this->hasRole('dosen') || $this->role === 'dosen';
    }

    public function isMahasiswa(): bool
    {
        return $this->hasRole('mahasiswa') || in_array($this->role, ['mahasiswa', 'student']);
    }

    public function isParent(): bool
    {
        return $this->hasRole('parents') || in_array($this->role, ['parent', 'parents']);
    }

    public function isFinance(): bool
    {
        return $this->hasRole('keuangan') || in_array($this->role, ['finance', 'keuangan']);
    }

    /**
     * Get all classes taught by this dosen
     */
    public function kelas()
    {
        return $this->hasMany(\App\Models\Kelas::class, 'dosen_id');
    }

    /**
     * Get all active schedules for this dosen
     */
    public function jadwals()
    {
        return $this->hasManyThrough(
            \App\Models\Jadwal::class,
            \App\Models\Kelas::class,
            'dosen_id', // Foreign key on kelas table
            'kelas_id', // Foreign key on jadwals table
            'id',       // Local key on users table
            'id'        // Local key on kelas table
        );
    }

    /**
     * Get jadwal proposals generated by this user (admin)
     */
    public function jadwalProposalsGenerated()
    {
        return $this->hasMany(\App\Models\JadwalProposal::class, 'generated_by');
    }

    /**
     * Get jadwal approvals made by this user
     */
    public function jadwalApprovals()
    {
        return $this->hasMany(\App\Models\JadwalApproval::class, 'approved_by');
    }
}
